#!/usr/bin/env bash
# Copies what is in server 01 to 02 and adding a custom header

sudo apt-get update
sudo apt-get install -y nginx

# what we need to display
echo "Hello World!" | sudo tee /var/www/html/index.html

# 302 redirections
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/NeneNafe permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
strings="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$strings/" /etc/nginx/sites-enabled/default

# Custom HTTP Response header
sudo sed -i "server_name _/a add_header X-server-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# checks for any config erros that may have occured
sudo nginx -t

# restart nginx
sudo service nginx restart
