#!/usr/bin/env bash
# installs the load balancer
# installs HAproxy to the load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend NeneNafe_frontend
        bind *:80
        mode http
        default_backend NeneNafe_backend

backend NeneNafe_backend
        balance roundrobin
        server 318591-web-01 100.26.132.15:80 check
        server 318591-web-02 100.25.118.3:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enables haproxy to be started by the init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# testing the haprocy config file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the haproxy restart
sudo service haproxy restart