#!/usr/bin/env bash
# debugging to know what is making nginx not listen on port 80

rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
