#!/usr/bin/env bash
#  a Bash script that displays the content of the file /etc/passwd
# The script displays:
# username
# user id
# Home directory path for the user

while IFT=":" read -r username _ uid _ home _
do
	echo "$username"
	echo "$uid"
	echo "$home"
done < /etc/passwd
