#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd,
# using the while loop + IFS

IFS=":"

while IFS=":" read -r username password _ gid user_info home_directory shell
do
	echo "The user $username is part of the $gid gang, lives in $home_directory and rides $shell."
	echo "USER ID's place is protected by the passcode $password, more info about the user here: $user_info"
	echo
done < /etc/passwd

IFS=" "
