#!/usr/bin/env bash
# A bash script that displays Best School 10 times,
# but for the 9th iteration displays Best School and Hi on a new line
count=0
while [ $count -lt 10 ]; do
	if [ $count -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	count=$((count + 1))
done
