#!/usr/bin/env bash
# a Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

for file in *
do
	if [ -f "$file" ] && [[ "$file" != .* ]]
then
	base_name=$(basename "$file")
	part_after_dash="${base_name#*-}"
	echo "$part_after_dash"
	fi
done
